apiVersion: v2
publisher: radon
name: template-library-plugin
version: 0.0.6
type: VS Code extension
displayName: template-library-plugin
title: RADON Template Library Plugin
description: Use Template Library directly from your IDE!
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/radon-h2020/radon-template-library-publishing-service-plugin
category: Other
spec:
  extensions:
    - https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-template-library/0.0.6/template-library-plugin-0.0.6.vsix